# Site settings
title: Learning Continuous Deployment
tagline: Continuous Deployment, Docker, Git
email:
description: > # this means to ignore newlines until "baseurl:"
  Hi, we are a handful of students
  and wanna have some fun with continuous deployment. :-)
baseurl: # the subpath of your site, e.g. /blog/
url: "https://learning-continuous-deployment.github.io" # the base hostname & protocol for your site
logourl: # /assets/images/logo.png # Site logo
author:
author_thumbnail: /assets/images/hdm-logo.png # Author avatar

excerpt_separator: <!--more-->

# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social:
    github: learning-continuous-deployment
    twitter:
    facebook:
    gplus:
    pinterest:

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: learningcontinuousdeployment

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-57974988-2
  google_webmaster_key:

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 15

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
